config/routes.rb
Rails.application.routes.draw do
  root 'admin/base#index' # ログイン画面をルートにする
  get '/admin' => 'admin/base#index'

  get 'home/index'

  get 'home/authentication'

  devise_for :people

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :admin, :all
    elsif user.member?
      can :member, :all
    end
  end

  # def initialize(user)
  #   # Define abilities for the passed in user here. For example:
  #   #
  #   #   user ||= User.new # guest user (not logged in)
  #   #   if user.admin?
  #   #     can :manage, :all
  #   #   else
  #   #     can :read, :all
  #   #   end
  #   #
  #   # The first argument to `can` is the action you are giving the user
  #   # permission to do.
  #   # If you pass :manage it will apply to every action. Other common actions
  #   # here are :read, :create, :update and :destroy.
  #   #
  #   # The second argument is the resource the user can perform the action on.
  #   # If you pass :all it will apply to every resource. Otherwise pass a Ruby
  #   # class of the resource.
  #   #
  #   # The third argument is an optional hash of conditions to further filter the
  #   # objects.
  #   # For example, here the user can only update published articles.
  #   #
  #   #   can :update, Article, :published => true
  #   #
  #   # See the wiki for details:
  #   # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  # end
end

app/models/corporation.rb
class Corporation < ActiveRecord::Base
  has_many :department
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :person
  belongs_to :corporation
end

app/models/employment_status.rb
class EmploymentStatus < ActiveRecord::Base
  has_many :person
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  has_many :person
end

app/models/person.rb
class Person < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  enum role: {admin: "admin", member: "member"}
  
  belongs_to :employment_status
  belongs_to :department
  belongs_to :enrollment
  belongs_to :title
end

app/models/title.rb
class Title < ActiveRecord::Base
  has_many :person
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :authenticate_person!
  
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def hello
    render text: "hello, world!"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_person!, only: :authentication
  def index
  end

  def authentication
  end
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/base/index.html.erb
<h1>Admin::Base#index</h1>
<p>Find me in app/views/admin/base/index.html.erb</p>

<% if can? :admin_read, current_person %>
<p>admin information</p>
<% end %>

<% if can? :member_read, current_person %>
<p>member information</p>
<% end %>

app/views/home/authentication.html.erb
<h1>Home#authentication</h1>
<p>Find me in app/views/home/authentication.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Empowerment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1>Empowerment</h1>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>